### PR TITLE
Revert "[WIP] Quick steps to contribution to this project"

### PR DESCRIPTION
**Pull request by SharatKuncha**
Reverts SharatKuncha/my-first-project#2

### CODE REVIEW

**Comment by SharatKuncha** [comment]
@ curtisberry

**Comment by SharatKuncha** [comment]
https://github.com/SharatKuncha/my-first-project/pull/3

**Comment by SharatKuncha** [comment]
@curtisberry

**Comment by SharatKuncha** [comment]
https://github.com/SharatKuncha/my-first-project/pull/3
@curtisberry

**Comment by curtisberry** [comment]
recieved your notice

**Pull request merged**
